### ISSUE TITLE
你好有没有关于维吾尔语词干提取的参考代码，谢谢

### ISSUE THREAD

**Issue by BadDeveloper2022** [gheyret/test_word2vec_uyghur#1]
你好有没有关于维吾尔语词干提取的参考代码，谢谢
خام سۆز ھەم تۈپ سۆزنى ئالدىغان پىروگىرامما بولسا ھەمبەھىرلەپ بەرگەن بولسىڭىز 
يېقىندا مەن elasticsearch قا بىر قاپچۇق يېزۋاتقان
رەھمەت سىزگە

**Comment by gheyret** [comment]
Weeleykum essalam,

Sizning demekchi bolghiningiz, Melum bir sozning tup sozini(yeni soz yiltizini) demekchimu?
mesilen: Uyghurning --> Uyghur
              yazdim --> yazmaq

degendek?
bundaq ambar mende yoq idi. 
Burun bireylen, 
Mecab degen Yaponche 形態素解析 qilidighan ambarni Uyghurchege maslashturghan idi.
Bu heqte :
http://tsumulab.org/papers/pdf/degree/2011_master_paerhati.pdf
https://www.anlp.jp/proceedings/annual_meeting/2007/pdf_dir/PD1-1.pdf
maqaliler yezilghan.

**Comment by BadDeveloper2022** [comment]
بولدۇ مەن كۆرۈپ باقاي
شۇنداق سۆز يىلتىزىنى ئېلىش
مېنىڭ قىلماقچى بولغىنىم
مەلۇم بىر جۈملە سۆز كەلسە
ئالدى بىلەن سۆز يىلتىزىنى ئېلىپ ھەر خىل سۆزلەرنى شەكللەندۈرۈش

**Comment by BadDeveloper2022** [comment]
ياپونچىكەن
ئىنگىلىزچىسى يوقما
